### ISSUE TITLE
singleSelection & groupBy

### ISSUE THREAD

**Issue by timoberlin** [CuppaLabs/angular2-multiselect-dropdown#401]
Is there any way to use the following configuration for a selection field:
                    singleSelection: true,
                    text: 'Please select',
                    enableSearchFilter: true,
                    groupBy: 'category'

Actually, when configuring the dropdown with singleSelection: true, no entries will be returned. When configured as singleSelection: false, entries can be selected.

In some cases we just need elements grouped by a category where only one element is assignable.

Thanks a lot for your help!

<img width="535" alt="empty" src="https://user-images.githubusercontent.com/2080312/60887090-cd307100-a253-11e9-8f91-3286d4f01499.png">

**Comment by pkoziol** [comment]
This sounds like basic functionality, so it should be marked as a bug not an enhancement.

**Comment by seenivasan097** [comment]
I am also facing same issue. It's working fine in Version 4.2.2. problem with version 4.2.7. Please fix this issue ASAP.

**Comment by CuppaLabs** [comment]
fixed. yet to publish package to NPM

**Comment by CuppaLabs** [comment]
fix available in v4.2.8

**Comment by timoberlin** [comment]
Hi there,

I've updated to: 
"angular2-multiselect-dropdown": "^4.6.2".

My configuration:
        SINGLE_CATEGORY_TOP: {
          text: 'Please select',
          singleSelection: true,
          enableSearchFilter: true,
          groupBy: 'category',
          position: 'top',
        },

Unfortunately, I still have this selector without any data as described in my first post. Could you give me a hint what I'm doing wrong?

Cheers!

**Comment by CuppaLabs** [comment]
@timoberlin I have written a stackblitz example with your configuration. Please refer to https://stackblitz.com/edit/angular2-multiselect-dropdown-q868lj . Please update the same to replicate the issue.
